
/* ==========================================================================
   VOICE SYSTEM — 7 Voices
   ========================================================================== */
const DEFAULT_VOICE='founder';
let currentVoice=ls.get('voice',DEFAULT_VOICE);

const VOICES={
founder:{
typed:['A small store, a big dream, 1955','We brought the Italian sub to Detroit','Three generations. One standard: quality.','Trust the crust. Trust the family.','70 years and still the original'],
'hero-title':'The Original Buscemi\'s',
'stat-1':'Years of Family Pride',
'stat-2':'Locations, One Family',
'stat-3':'The Year It All Started',
'menu-title':'Our Menu, Our Legacy',
'menu-subtitle':'Every item on this menu carries our family name. That means something. We perfected these recipes over decades because Paul Buscemi never accepted anything less than the best.',
'card-1-title':'Detroit-Style Pizza',
'card-1-desc':'My father spent years on this recipe. The dough, the sauce, every ingredient tested until it was right. That crispy cheese edge? That\'s not an accident. That\'s obsession.',
'card-2-title':'The Torpedo &amp; Baby Sub',
'card-2-desc':'We were the first to bring the Italian sub to Detroit. That\'s not marketing talk. That\'s history. The Torpedo and Baby Sub carry our trademark because we earned it.',
'card-3-title':'Specialty Pizza',
'card-3-desc':'BBQ Chicken, Supreme, Hawaiian. We took our perfected base and built specialties that keep people coming back. Every one made with the same care as the original.',
'card-4-title':'Calzones &amp; Rolls',
'card-4-desc':'Fresh dough, stuffed right, sealed and baked to order. Steak and cheese, ham and cheese, Supreme. Simple food done the way it should be.',
'card-5-title':'Party Paks &amp; Catering',
'card-5-desc':'When your family gathers, our family feeds them. Party paks, full trays, family meal deals. We\'ve been the go-to for Michigan gatherings since before most chains existed.',
'card-6-title':'Sides &amp; Salads',
'card-6-desc':'Cheese Stix with our marinara, fresh salads. Nothing fancy. Just good food that rounds out the meal the way it should be.',
'about-title':'How It Started, Why It Lasts',
'about-text':'I started with nothing but a small party store and the belief that if you make the best food, people will come. They came. When I created the Torpedo, Detroit had never seen an Italian sub like it. When I perfected the pizza, nobody could match it. My son Anthony carries this forward. We franchised in 1974 because we knew what we had was worth sharing. Fifty locations later, the commitment hasn\'t changed.',
'values-title':'What Sets Us Apart',
'val-1-desc':'My father tested dough recipes for years. Not months. Years. Every ingredient had to meet his standard. That standard hasn\'t dropped since 1955.',
'val-2-desc':'From Paul to Anthony. This isn\'t a corporation. It\'s a family that puts their name on every box because they stand behind every bite.',
'val-3-desc':'First Italian sub in Detroit. First franchised Party Shoppe in Michigan. Being original isn\'t a slogan. It\'s our history.',
'test-1':'My grandfather used to take me to Buscemi\'s in the 60s. I take my grandkids now. Same quality. That says everything.',
'test-2':'The Torpedo is a Detroit institution. Period. Nothing else comes close and I\'ve tried them all.',
'test-3':'Every birthday, every graduation, every game day for 30 years. Buscemi\'s party paks are part of the family.',
'franchise-title':'Carry the Buscemi\'s Name',
'franchise-text':'We franchise because we believe in sharing what works. A Buscemi\'s license gives you our recipes, our buying power, our marketing, and a name that Michigan trusts. We were first to franchise the Party Shoppe. We know how to build success together.',
'cta-title':'The Original. Since 1955.',
'cta-subtitle':'Order online, visit your nearest location, or reach out. The Buscemi family is still here, still cooking, still proud.',
'footer-about':'Founded by Paul A. Buscemi in 1955. Now led by Anthony Buscemi. Three generations, 50+ locations, and the same promise: GREAT ITALIAN TASTE. This is our family. This is our food.',
'faq-1':'Detroit-style pizza is baked in a square steel pan. Thick, airy dough. Crispy caramelized cheese edge. My father perfected this recipe through years of testing. The crust is the foundation. Trust it.',
'faq-2':'Yes. Many locations offer online ordering. Check your local store\'s availability and order right from your phone.',
'faq-3':'We\'ve been catering Michigan events since the beginning. Party paks, quarter trays, full trays. Call your local Buscemi\'s for pricing.',
'faq-4':'Visit our Locations page. Enter your zip code or browse the full list of 50+ stores with addresses and phone numbers.',
'faq-5':'The Torpedo is our full-size Italian submarine sandwich. Trademarked. First of its kind in Detroit. Italian meats, cheese, fresh toppings. Hot or cold. The Baby Sub is the smaller version.',
'faq-6':'Visit our Franchise page or contact us. We\'ve been franchising since 1974. You get our recipes, buying power, marketing support, and a 70-year reputation.'
},

pizzaiolo:{
typed:['Dough that rises right takes patience','Sauce from scratch, cheese to the edge','Every pizza tells the story of its maker','The oven knows when the crust is perfect','Crafted by hand, perfected by time'],
'hero-title':'Crafted With Fire &amp; Tradition',
'stat-1':'Years Perfecting the Craft',
'stat-2':'Ovens Running Daily',
'stat-3':'Recipes Born This Year',
'menu-title':'From Our Kitchen to Your Table',
'menu-subtitle':'Behind every item is a recipe refined over decades. The dough rests until it\'s ready. The sauce simmers until the flavor is right. We don\'t rush. Good food tells you when it\'s done.',
'card-1-title':'The Square Pie',
'card-1-desc':'Thick pan dough, pressed into steel, topped edge to edge. The cheese caramelizes against the pan walls into a golden crust. This is Detroit-style done by the people who perfected it.',
'card-2-title':'Italian Subs',
'card-2-desc':'Fresh bread, layered meats sliced to order, provolone, the right ratio of oil to vinegar. The Torpedo is a masterclass in sandwich construction. Every layer matters.',
'card-3-title':'Specialty Creations',
'card-3-desc':'Our BBQ Chicken uses a house glaze. The Supreme gets double cheese. Every specialty starts with the same base we spent decades on, then we add our own twist.',
'card-4-title':'Calzones &amp; Rolls',
'card-4-desc':'Same dough as our pizza, folded and sealed by hand. The Steak and Cheese gets seared filling before it goes in the pocket. It\'s not just stuffed dough. It\'s engineered.',
'card-5-title':'Feeds a Crowd',
'card-5-desc':'Party trays and paks built for volume without sacrificing quality. The full tray gets the same attention as a single pie. Scale doesn\'t mean shortcuts.',
'card-6-title':'Cheese Stix &amp; Fresh Sides',
'card-6-desc':'Our Cheese Stix use the same dough and cheese as the pizza. Dipped in house marinara. Garden salads with fresh produce. Simple, clean, complementary.',
'about-title':'The Craft Behind the Crust',
'about-text':'Paul Buscemi didn\'t just make pizza. He studied it. Years of testing dough hydration, fermentation times, sauce acidity, cheese melting points. The recipe that came out of that process is what we still use today. Every pizzaiolo in a Buscemi\'s kitchen learns the same techniques, the same standards, the same respect for the craft that started in 1955.',
'values-title':'The Craft Behind Every Bite',
'val-1-desc':'We source carefully. Flour, tomatoes, cheese. The recipe only works when every ingredient meets the spec. No substitutions, no shortcuts.',
'val-2-desc':'Techniques passed from Paul to Anthony to every kitchen that carries the name. You learn the feel of the dough before you learn the recipe.',
'val-3-desc':'Detroit-style isn\'t just a shape. It\'s a method. Pan selection, oil distribution, cheese placement. We wrote the playbook.',
'test-1':'You can taste the difference between Buscemi\'s and everyone else. The crust alone. There\'s a crunch and then a softness inside that nobody matches.',
'test-2':'My wife is from New Jersey. She said the Torpedo is better than anything on the shore. Coming from her, that\'s the highest compliment.',
'test-3':'I ordered a full tray for my restaurant\'s staff party. Professional cooks tearing into Buscemi\'s pizza. That tells you everything.',
'franchise-title':'Bring the Craft to Your Community',
'franchise-text':'Every franchise location gets trained in our methods. The dough technique, the sauce process, the oven management. You\'re not just buying a name. You\'re learning a craft backed by seven decades of refinement.',
'cta-title':'Made Right. Every Time.',
'cta-subtitle':'Order our handcrafted pizza and subs online, or find a kitchen near you. The craft is in every bite.',
'footer-about':'Detroit-style pizza and Italian subs crafted using recipes perfected since 1955. Every location upholds the same techniques, the same ingredients, the same standards Paul Buscemi set in his first kitchen.',
'faq-1':'Detroit-style pizza uses a thick, airy dough pressed into a blue steel pan. Cheese goes edge-to-edge, caramelizing against the pan walls. The result is a crispy, golden cheese crust with a soft interior. Our recipe took years to develop.',
'faq-2':'Yes. Online ordering is available at many locations. Select your store, build your order, and we\'ll have it ready for pickup.',
'faq-3':'Full catering available. Quarter trays, full trays, party paks. Every item prepared with the same standards as individual orders.',
'faq-4':'Our Locations page has a zip code search and full directory. 50+ stores across Michigan, each with address and direct phone line.',
'faq-5':'The Torpedo is a full-length Italian sub built on fresh bread with layered meats and cheese. Created by Paul Buscemi. First Italian sub in Detroit. Available hot or cold. The Baby Sub is the half portion.',
'faq-6':'We train every franchisee in our kitchen methods. Contact us through the Franchise page. 50+ years of franchise experience.'
},

neighbor:{
typed:['The place on the corner everyone knows','Grab a slice, catch up with friends','Friday night means Buscemi\'s','Your neighborhood party store since forever','Cold beer, hot pizza, good people'],
'hero-title':'Your Neighborhood Buscemi\'s',
'stat-1':'Years in Your Neighborhood',
'stat-2':'Spots to Grab a Slice',
'stat-3':'Feeding Michigan Since',
'menu-title':'The Usual? Coming Right Up.',
'menu-subtitle':'You already know what\'s good. But if you\'re new here, let us catch you up. Everything\'s made fresh and nothing on this menu will let you down.',
'card-1-title':'Square Pizza',
'card-1-desc':'The one everybody gets. Thick, cheesy, crispy edges. Grab a whole tray for the family or a couple slices on your way home. It never gets old.',
'card-2-title':'Torpedo &amp; Baby Sub',
'card-2-desc':'The Torpedo is that giant Italian sub you\'ve been hearing about since you moved to the area. The Baby Sub is the same thing, just more reasonable for lunch. Both are incredible.',
'card-3-title':'Specialty Pies',
'card-3-desc':'When you want to switch it up from the usual. BBQ Chicken is a crowd favorite, the Supreme is loaded, and the Hawaiian is better than you\'d expect.',
'card-4-title':'Calzones',
'card-4-desc':'Basically a pizza folded in half and stuffed. Steak and cheese is the move. Grab one on a cold day and you\'re set.',
'card-5-title':'Party Food',
'card-5-desc':'Having people over? Just call Buscemi\'s. Party paks, trays, the whole deal. Everyone knows the drill. It\'s what you do around here.',
'card-6-title':'Stix &amp; Salads',
'card-6-desc':'Cheese Stix are perfect for sharing. Salads are there if you need to balance things out. No judgment either way.',
'about-title':'Part of the Block Since \'55',
'about-text':'Buscemi\'s has been on the corner longer than most of us have been alive. Paul started it in 1955, his son Anthony keeps it going. It\'s the kind of place where the person behind the counter knows your order, your name, and probably your family. Fifty-plus locations now, but every one still feels like your local spot.',
'values-title':'Why Everyone Picks Buscemi\'s',
'val-1-desc':'Same recipes for 70 years. Your parents ordered the same pizza you\'re ordering now. That consistency is rare and it matters.',
'val-2-desc':'The Buscemi family still runs this thing. Not some corporate office in another state. Real people who care about the food and the community.',
'val-3-desc':'Buscemi\'s was here before the chains moved in. Detroit original, Michigan loyal. That\'s not something you can buy.',
'test-1':'Friday night tradition. Kids run in, I order the usual, everyone\'s happy. Been doing it for fifteen years straight.',
'test-2':'Moved to Sterling Heights from out of state. My neighbor said "you gotta try Buscemi\'s." Now I\'m the one telling new neighbors the same thing.',
'test-3':'Every party, every cookout, every "what should we get for dinner" moment. The answer is always Buscemi\'s. Always.',
'franchise-title':'Be the Local Buscemi\'s',
'franchise-text':'People love their local Buscemi\'s. It becomes part of the neighborhood. If you want to run a place that people actually care about, not just another chain location, this is it. We\'ve been doing this since 1974 and the model works.',
'cta-title':'Hungry? Yeah, We Got You.',
'cta-subtitle':'Order online, swing by, or give us a call. Your Buscemi\'s is probably closer than you think.',
'footer-about':'Your neighborhood pizza and sub shop since 1955. 50+ locations across Michigan. Cold drinks, hot food, and the kind of place where everybody knows your order.',
'faq-1':'It\'s thick pizza baked in a square pan with cheese all the way to the edges. The edges get crispy and golden. It\'s a Michigan thing and Buscemi\'s does it better than anyone.',
'faq-2':'Yeah, a lot of locations do online ordering. Check if yours is set up and order from your couch.',
'faq-3':'For sure. Party paks, big trays, all of it. Just call your local spot and they\'ll set you up.',
'faq-4':'Hit up the Locations page. Type in your zip code. There are 50-plus stores so there\'s probably one right near you.',
'faq-5':'It\'s a big Italian sub. Like, the real deal. Meats, cheese, the works. The Baby Sub is just a smaller version. Both are excellent.',
'faq-6':'Check out the Franchise page on the site. They\'ve been franchising since \'74 so they definitely know the deal.'
},

critic:{
typed:['A culinary institution meriting serious attention','Where Detroit\'s pizza tradition reaches its apex','Remarkably consistent across five decades','The submarine sandwich, elevated','An establishment that rewards repeated visits'],
'hero-title':'The Definitive Detroit Pizzeria',
'stat-1':'Years of Culinary Consistency',
'stat-2':'Locations Maintaining Standards',
'stat-3':'Established',
'menu-title':'A Menu Refined by Seven Decades',
'menu-subtitle':'What distinguishes Buscemi\'s is not ambition but discipline. The menu has been honed over generations, each item reflecting a clear philosophy: master the fundamentals, then execute them relentlessly.',
'card-1-title':'Detroit-Style Pizza',
'card-1-desc':'The square pizza achieves what many attempt and few accomplish: a crust that is simultaneously airy and crisp, with a caramelized cheese perimeter that provides textural contrast. The sauce-to-cheese ratio demonstrates careful calibration.',
'card-2-title':'The Torpedo &amp; Baby Sub',
'card-2-desc':'Historically significant as the first Italian submarine sandwich in the Detroit market. The construction shows proper layering technique. Meats are sliced appropriately, bread holds without disintegrating. A reliable benchmark.',
'card-3-title':'Specialty Pizzas',
'card-3-desc':'The BBQ Chicken demonstrates restraint in its sauce application. The Supreme maintains balance despite generous toppings. Each specialty builds upon the proven foundation without overcomplicating it.',
'card-4-title':'Calzones &amp; Pizza Rolls',
'card-4-desc':'The calzone employs the same proven dough, which provides an immediate advantage over competitors. Fillings are proportional. The seal holds through baking without leaking. Competent execution.',
'card-5-title':'Catering &amp; Party Service',
'card-5-desc':'Large-format preparation often suffers quality loss. Buscemi\'s manages to scale without the typical degradation. The party pak concept is efficient and well-portioned for group consumption.',
'card-6-title':'Accompaniments',
'card-6-desc':'The Cheese Stix benefit from the house dough and are best judged by their marinara, which maintains the same depth as the pizza sauce. Salads are fresh and uncomplicated.',
'about-title':'A Study in Culinary Persistence',
'about-text':'The Buscemi narrative is one of methodical refinement. Paul A. Buscemi, beginning in 1955, approached pizza-making with the temperament of a researcher: testing variables, adjusting parameters, and refusing to release a product until it met his exacting standards. The result is a recipe that has remained essentially unchanged for seven decades. The franchise expansion under Anthony Buscemi has, remarkably, not diluted the quality. Consistency across 50+ locations is a genuine achievement in this market.',
'values-title':'Distinguishing Characteristics',
'val-1-desc':'Ingredient sourcing appears consistent and deliberate. The dough exhibits the same hydration and fermentation characteristics across locations. This level of standardization is noteworthy.',
'val-2-desc':'Family stewardship provides continuity that corporate structures rarely match. The institutional knowledge embedded in the Buscemi operation is a genuine competitive advantage.',
'val-3-desc':'Provenance matters. Being the originator of the Italian sub in Detroit is not merely historical trivia. It represents foundational expertise that informs every aspect of the operation.',
'test-1':'I\'ve reviewed pizza across three states. The Buscemi\'s square pizza remains in my top tier. The crust architecture alone warrants the visit.',
'test-2':'The Torpedo sub demonstrates what happens when a single item receives seven decades of refinement. Remarkably, it hasn\'t been "improved" into mediocrity.',
'test-3':'Ordered catering for a 200-person event. The quality held at volume. That\'s the true test of a food operation and Buscemi\'s passed it.',
'franchise-title':'A Proven Model Worth Examining',
'franchise-text':'The Buscemi\'s franchise model has operated since 1974. The longevity alone suggests viability. What makes it particularly interesting is the retention of quality standards across independently operated locations. Prospective franchisees receive not just a brand, but a tested methodology.',
'cta-title':'A Visit Is Warranted',
'cta-subtitle':'Whether ordering online or visiting in person, Buscemi\'s delivers a consistent experience that merits your attention. Seven decades of operation is its own review.',
'footer-about':'Established 1955. An enduring presence in Michigan\'s culinary landscape. Detroit-style pizza and Italian subs executed with the consistency and care that comes from seven decades of focused refinement.',
'faq-1':'Detroit-style pizza employs a thick, well-hydrated dough baked in a square steel pan. Cheese is applied to the edges, where it caramelizes against the pan surface creating a distinctive crispy perimeter. Buscemi\'s version is among the benchmark examples.',
'faq-2':'Online ordering is available at participating locations. The platform is functional and straightforward.',
'faq-3':'Full catering service is available. The quality holds at volume, which is the relevant metric for catering evaluation.',
'faq-4':'The Locations page provides a comprehensive directory with zip code search functionality. 50+ locations across Michigan.',
'faq-5':'The Torpedo is a full-format Italian submarine sandwich, trademarked by Buscemi\'s. First Italian sub offered in the Detroit market. Available in hot or cold preparation. The Baby Sub is the reduced-format option.',
'faq-6':'Franchise inquiries are handled through the website. The program has operated since 1974 with demonstrable success.'
},

detroit:{
typed:['Born in the D, raised on square pizza','This is a Detroit thing, you wouldn\'t get it','Macomb County runs on Buscemi\'s','Motor City food, no pretense, all flavor','Michigan made. Michigan proud.'],
'hero-title':'Straight Outta Detroit',
'stat-1':'Years Repping the D',
'stat-2':'Locations Across the Mitten',
'stat-3':'Born in Detroit',
'menu-title':'Detroit Eats. The Real Ones.',
'menu-subtitle':'This isn\'t artisan anything. This is the food Detroit was built on. Square pizza. Italian subs. The stuff your parents grew up on and your kids are growing up on now.',
'card-1-title':'Square Pizza',
'card-1-desc':'Detroit-style, baby. Square pan, crispy cheese edges, thick crust that actually has flavor. This is what the rest of the country is trying to copy. We\'ve been doing it since \'55.',
'card-2-title':'The Torpedo',
'card-2-desc':'First Italian sub in the D. First. Before anybody else was doing it. The Torpedo is a Detroit staple and if you haven\'t had one, you haven\'t really been to Metro Detroit.',
'card-3-title':'Loaded Specialty Pies',
'card-3-desc':'Supreme, BBQ Chicken, Taco pizza. All built on that same legendary base. Detroit doesn\'t do boring food and neither do we.',
'card-4-title':'Calzones',
'card-4-desc':'Hot, stuffed, perfect for a cold Michigan winter night. Steak and cheese calzone from Buscemi\'s hits different when it\'s 15 degrees outside.',
'card-5-title':'Party Paks',
'card-5-desc':'You throwing a party in Metro Detroit without Buscemi\'s? That\'s a violation. Party paks and trays are literally how this area celebrates everything.',
'card-6-title':'The Sides',
'card-6-desc':'Cheese Stix for the table, salad if your doctor\'s watching. Either way, you\'re covered.',
'about-title':'A Detroit Story',
'about-text':'1955. Detroit. Paul Buscemi opens a small party store with big ambitions. He creates the Torpedo, Detroit\'s first Italian sub. He perfects a square pizza recipe that becomes legendary. His son Anthony takes the wheel, franchises the concept, and now there are 50-plus locations across Michigan. This isn\'t a chain that moved here. This is a chain that started here. Detroit-born, Michigan-raised, still family-owned.',
'values-title':'Detroit Different',
'val-1-desc':'Same recipe since Eisenhower was president. Detroit doesn\'t play when it comes to food quality and neither does Buscemi\'s.',
'val-2-desc':'Paul to Anthony. Family business in a city that respects family businesses. No corporate owners, no out-of-state headquarters.',
'val-3-desc':'Detroit original. Not a franchise from somewhere else. Not a concept imported from another city. Born here. Still here. That\'s real.',
'test-1':'Grew up in Warren eating Buscemi\'s every week. Moved to Chicago for work. Moved back. The pizza was a factor. Not kidding.',
'test-2':'The Torpedo is Detroit\'s best-kept secret, except it\'s not a secret to anyone who lives here. It\'s just a fact.',
'test-3':'Lions game day. Pistons watch party. Random Tuesday. Buscemi\'s party pak is the default. Has been for decades.',
'franchise-title':'Rep the D. Own a Buscemi\'s.',
'franchise-text':'If you want to bring real Detroit food to your area, Buscemi\'s is the move. We\'ve been franchising since \'74. You get the recipes, the training, the brand, and the reputation that Michigan already trusts. This isn\'t starting from scratch. This is joining the team.',
'cta-title':'Order Up, Detroit.',
'cta-subtitle':'You know what you want. Get it online, find your spot, or hit us up. 70 years deep and still going hard.',
'footer-about':'Detroit-born since 1955. Square pizza, Torpedo subs, party shoppes. 50+ locations across Michigan. Family-owned, locally operated, and proudly from the D.',
'faq-1':'Square pan, thick dough, cheese melted to the very edge where it gets crispy and golden. That\'s Detroit-style. We didn\'t invent the concept, but we perfected it.',
'faq-2':'Yeah, online ordering works at a lot of our spots. Check your local one.',
'faq-3':'Catering is what we do. Party paks, trays, the works. Call your nearest location.',
'faq-4':'Locations page on the site. Zip code search. 50+ stores across the Mitten.',
'faq-5':'Full-size Italian sub. First one ever served in Detroit. Italian meats, cheese, toppings. Hot or cold. Baby Sub is the shorter version. Both are elite.',
'faq-6':'Hit the Franchise page. We\'ve been doing this since 1974. The model works.'
},

gameday:{
typed:['Wings at halftime, pizza for the fourth quarter','Feed the whole squad, no leftovers','Watch party starter pack: Buscemi\'s','Tailgate fuel since 1955','The official food of your living room arena'],
'hero-title':'Game On. Pizza\'s Here.',
'stat-1':'Years Fueling Game Days',
'stat-2':'Party Headquarters',
'stat-3':'Feeding Fans Since',
'menu-title':'The Game Day Lineup',
'menu-subtitle':'Whether it\'s the Lions, Tigers, Red Wings, or just a random Thursday night hangout, Buscemi\'s has the food that makes any gathering better. Order big. You\'ll need it.',
'card-1-title':'Square Pizza',
'card-1-desc':'The MVP of game day food. One tray feeds four, two trays feeds eight, and nobody argues about toppings when you get cheese. Crispy edges are bonus points.',
'card-2-title':'Sub Trays',
'card-2-desc':'Torpedo and Baby Sub trays for the group. Cut into sections, easy to grab during a timeout. The Italian sub that wins every taste test at every party.',
'card-3-title':'Specialty Pizzas',
'card-3-desc':'Mix it up for the crowd. BBQ Chicken for the adventurous, Supreme for the people who want everything, regular cheese for the purists. Cover all your bases.',
'card-4-title':'Calzones',
'card-4-desc':'Hand-held, no plates needed, stuffed with good stuff. Steak and cheese calzone is basically the perfect food for standing around the TV.',
'card-5-title':'Party Paks &amp; Full Trays',
'card-5-desc':'This is what you came for. Party paks with pizza AND subs. Quarter trays, full trays, family meal deals. One call and your whole event is handled.',
'card-6-title':'Cheese Stix &amp; Sides',
'card-6-desc':'Cheese Stix are the appetizer that never makes it to the main event. Order extra. The salads are there for anyone trying to keep it balanced. Good luck.',
'about-title':'The MVP of Michigan Gatherings',
'about-text':'Since 1955, Buscemi\'s has been the go-to for every party, every celebration, every game day in Metro Detroit. Paul Buscemi started making pizza and subs. His son Anthony scaled it to 50+ locations. But the real win? Being the name people call first when they need to feed a crowd. Graduation parties, Super Bowl Sundays, Lions home openers, backyard cookouts. If people are gathering in Michigan, Buscemi\'s is probably involved.',
'values-title':'Built for the Big Moments',
'val-1-desc':'Consistent quality means you know exactly what you\'re getting every time you order for a group. No surprises, no disappointments, just reliable food.',
'val-2-desc':'Family-run means they understand family gatherings. These aren\'t corporate portions. These are "everyone needs to eat" portions.',
'val-3-desc':'The original party store. Literally. Pizza, subs, drinks, snacks, all in one stop. Game day logistics simplified since 1955.',
'test-1':'Super Bowl party every year. Buscemi\'s party pak. Twenty people, zero complaints. That\'s a twelve-year streak.',
'test-2':'Fantasy draft night tradition: two Torpedo trays and a couple square pizzas. The food is the best part of the night. Sorry, guys.',
'test-3':'Catered my daughter\'s graduation party. 80 people. Full trays of pizza and subs. Gone in an hour. Absolute hit.',
'franchise-title':'Own the Party',
'franchise-text':'People need a place to get party food. Buscemi\'s is that place in Michigan and it could be that place wherever you are. Pizza, subs, drinks, convenience. One-stop party shop with 70 years of brand trust behind it.',
'cta-title':'Don\'t Show Up Empty-Handed.',
'cta-subtitle':'Order the party pak, grab the trays, be the hero. Online ordering makes it easy. Your squad will thank you.',
'footer-about':'The official food of Michigan gatherings since 1955. Party paks, pizza trays, sub platters, and everything you need to feed the crew. 50+ locations, one mission: make your party legendary.',
'faq-1':'Thick square pizza baked in a steel pan. Crispy cheese edges, airy crust. Perfect for cutting into squares and sharing at any gathering. Feeds a crowd efficiently.',
'faq-2':'Yes. Online ordering at participating locations. Get your order in early on game days because everyone else has the same idea.',
'faq-3':'Absolutely. Party paks, quarter trays, full trays. Built for events. Call ahead for large orders.',
'faq-4':'Locations page, zip code search. 50+ stores. Find the closest one for quickest pickup.',
'faq-5':'Big Italian sub, feeds one very hungry person or two reasonable people. The Baby Sub is the single-serving version. Both are party favorites.',
'faq-6':'Franchise page has the details. Since 1974, proven model, great for anyone who wants to be the local party food headquarters.'
},

franchise:{
typed:['A proven model since 1974','Multiple profit centers under one roof','70 years of brand equity working for you','Join Michigan\'s most trusted food brand','Better buying power. Better margins.'],
'hero-title':'A Franchise Built to Perform',
'stat-1':'Years of Proven Operations',
'stat-2':'Successful Locations',
'stat-3':'Franchising Since 1974',
'menu-title':'A Menu Engineered for Profitability',
'menu-subtitle':'Every item on the Buscemi\'s menu has been refined for both customer satisfaction and operational efficiency. High-margin products, streamlined prep, and consistent demand across dayparts.',
'card-1-title':'Detroit-Style Pizza',
'card-1-desc':'Our highest-volume product. Proven recipe with consistent demand. Steel pan method ensures uniform results across operators. Strong margins with controlled ingredient costs.',
'card-2-title':'Italian Subs',
'card-2-desc':'Trademarked products with built-in brand recognition. The Torpedo and Baby Sub drive repeat visits and maintain strong per-unit margins. Low waste, efficient prep.',
'card-3-title':'Specialty Menu',
'card-3-desc':'Premium-priced specialty items increase average ticket value. Shared ingredients with base pizza minimize inventory complexity while offering menu variety.',
'card-4-title':'Calzones &amp; Rolls',
'card-4-desc':'Utilizes existing dough and topping inventory. No additional equipment required. Provides menu diversity without operational complexity. Strong lunch-hour performer.',
'card-5-title':'Catering &amp; Party Paks',
'card-5-desc':'High-value large-format orders that maximize kitchen throughput. Party paks and tray orders represent significant revenue per transaction with excellent margins.',
'card-6-title':'Complementary Items',
'card-6-desc':'Cheese Stix and salads round out the ticket. Add-on items with strong margins that require minimal additional prep time.',
'about-title':'The Business Behind the Brand',
'about-text':'Buscemi\'s was founded in 1955 and began franchising in 1974, making it one of the longest-operating franchise systems in Michigan\'s food service industry. The model combines pizza, subs, and the Party Shoppe convenience concept under one roof, creating multiple profit centers per location. With 50+ operating locations, the system has demonstrated scalability while maintaining brand standards and customer satisfaction.',
'values-title':'Competitive Advantages',
'val-1-desc':'Standardized recipes and supplier relationships ensure consistent food costs. No guesswork in ingredient procurement or portion control.',
'val-2-desc':'Family leadership provides stability and long-term strategic thinking. No quarterly earnings pressure driving short-term decisions.',
'val-3-desc':'70+ years of brand awareness in Michigan. Customer acquisition costs are significantly lower than starting an independent concept.',
'test-1':'Opened my Buscemi\'s location three years ago. The brand recognition did half the marketing work for me. Profitable by month eight.',
'test-2':'Transitioned from corporate food service to franchise ownership. The training program was thorough and the ongoing support is real.',
'test-3':'Running two locations now. The systems are tight enough to manage both efficiently. Looking at a third.',
'franchise-title':'The Opportunity',
'franchise-text':'A Buscemi\'s franchise offers multiple profit centers: pizza, subs, convenience, beverages. You receive comprehensive training, established supplier relationships, marketing support, and 70 years of brand equity. The Party Shoppe model captures traffic across all dayparts and occasions.',
'cta-title':'Ready to Build Something?',
'cta-subtitle':'Contact us to discuss franchise opportunities. Established systems, proven economics, and a brand Michigan already trusts.',
'footer-about':'Original Buscemi\'s franchise system. Operating since 1955, franchising since 1974. 50+ locations across Michigan. Multiple profit centers, proven economics, and seven decades of brand equity.',
'faq-1':'Detroit-style pizza is a thick, square pizza baked in a steel pan with cheese applied to the edges. The format is efficient to produce, consistent in quality, and has strong market demand in Michigan and nationally.',
'faq-2':'Online ordering is integrated at participating locations. Digital ordering channels increase average ticket size and improve kitchen scheduling.',
'faq-3':'Catering is a significant revenue stream. Large-format orders with premium pricing and efficient preparation. Full support provided.',
'faq-4':'Our Locations page features zip-code search across 50+ Michigan stores. Each location independently operated under the franchise system.',
'faq-5':'Trademarked Italian sub product line. The Torpedo (full) and Baby Sub (half) are signature items with strong brand recognition and repeat purchase rates.',
'faq-6':'Submit an inquiry through our Franchise page. The process includes discovery, qualification, training, site selection support, and ongoing operational guidance.'
}
};

/* ---- Voice Toggle ---- */
const voiceToggle=$('.voice-toggle');
const voiceSwitcher=$('.voice-switcher');
if(voiceToggle){
  voiceToggle.addEventListener('click',()=>voiceSwitcher.classList.toggle('expanded'));
}

function applyVoice(v){
  currentVoice=v;ls.set('voice',v);
  const data=VOICES[v];if(!data)return;
  if(data.typed)typedPhrases=data.typed;
  const els=$$('[data-voice-key]');
  els.forEach(el=>el.classList.add('voice-fading'));
  setTimeout(()=>{
    els.forEach(el=>{
      const key=el.dataset.voiceKey;
      if(data[key]!==undefined)el.innerHTML=data[key];
    });
    els.forEach(el=>el.classList.remove('voice-fading'));
  },300);
  $$('.voice-dot').forEach(d=>d.classList.toggle('active',d.dataset.voice===v));
}
applyVoice(currentVoice);
$$('.voice-dot').forEach(d=>{
  d.addEventListener('click',()=>applyVoice(d.dataset.voice));
  d.addEventListener('keydown',e=>{if(e.key==='Enter')applyVoice(d.dataset.voice)});
});

/* ---- Fallback reveal for elements in viewport at load ---- */
setTimeout(()=>{$$('.reveal:not(.visible)').forEach(el=>{const r=el.getBoundingClientRect();if(r.top<window.innerHeight)el.classList.add('visible')})},2000);

